package pi.db.piversionbd.entities.score;

public enum AdherenceEventType {
    ONBOARDING_MEDICAL_BASELINE,
    CLAIM_APPROVED_BONUS,
    CLAIM_REJECTED_PENALTY,
    DOCUMENT_VERIFIED_BONUS,
    FRAUD_FLAG_PENALTY,
    MANUAL_REVIEW_PENDING,
    REWARD_REDEMPTION
}
